/**
 * Every piece of writing on the site, described once.
 *
 * The values here are the words the site launched with — the seed. Once a page
 * has been saved in the panel its words come from Firestore instead, so editing
 * a heading is a panel change rather than a deploy. Nothing here touches
 * Firestore, so a client component can import the types; copy.ts does the
 * reading and writing.
 *
 * {fete}, {cosplay} and {seats} are replaced with the live values as a page is
 * read, so copy can quote a price without going stale when it changes.
 */

export type CopySlot = {
  key: string;
  label: string;
  type: "text" | "longtext";
  /** The words as the site launched with them. */
  value: string;
  hint?: string;
};

export type CopyGroup = {
  key: string;
  title: string;
  blurb: string;
  slots: CopySlot[];
};

export const COPY_GROUPS: CopyGroup[] = [
  {
    key: "home",
    title: "Home page",
    blurb: "The hero, the date card, the doors and the bands between them.",
    slots: [
      { key: "heroBadge", label: "Hero pill badge", type: "text", value: "FIRST EDITION · A SCHOOL THAT THREW A CARNIVAL", hint: "The · separators are part of the text; keep them if you reword." },
      { key: "heroTitle", label: "Hero headline", type: "text", value: "THE VOICE OF HAZARIBAGH" },
      { key: "heroTagline", label: "Hero tagline", type: "text", value: "MUSIC · MOMENTS · MEMORIES" },
      { key: "heroIntro", label: "Hero intro paragraph", type: "longtext", value: "One Saturday, the Elden Heights grounds stop behaving like a school. Cosplayers take the corridors, the fete eats your pocket money, and somebody very famous walks out on stage at 4:30 — we're not telling you who yet.", hint: "The 4:30 stage time is typed into this sentence, not read from settings — edit it here if the time changes." },
      { key: "heroConcertCta", label: "Hero button — concert", type: "text", value: "GUESS WHO →", hint: "The arrow is part of the label text." },
      { key: "heroTicketsCta", label: "Hero button — passes", type: "text", value: "GRAB A PASS" },
      { key: "heroCosplayCta", label: "Hero button — cosplay", type: "text", value: "ENTER THE COSPLAY ARENA" },
      { key: "dateCardEyebrow", label: "Date card — left kicker", type: "text", value: "IT ALL HAPPENS IN" },
      { key: "dateCardSealedNote", label: "Date card — sealed note", type: "longtext", value: "The council has picked it. The council is sitting on it.", hint: "Shown only when the fest date is still sealed." },
      { key: "dateCardExactEyebrow", label: "Date card — right kicker", type: "text", value: "THE EXACT DATE" },
      { key: "dateCardDaySealedLabel", label: "Sealed flag — day only", type: "text", value: "THE DAY IS STILL SEALED" },
      { key: "dateCardMonthSealedLabel", label: "Sealed flag — day and month", type: "text", value: "DAY AND MONTH SEALED" },
      { key: "dateCardSealedBlurb", label: "Date card — reveal blurb", type: "longtext", value: "Sealed until the guests are out. The day drops with the final reveal — and passes open the same hour.", hint: "Shown in place of the countdown when the countdown is switched off." },
      { key: "heroHoursNote", label: "Hero footnote — gates and hours", type: "text", value: "ONE SATURDAY · GATES 9:00 AM · LAST ENCORE 6:00 PM", hint: "Gate and encore times are typed into this line, not read from settings." },
      { key: "aboutEyebrow", label: "About — kicker", type: "text", value: "WHAT IS THIS MADNESS" },
      { key: "aboutTitle", label: "About — heading", type: "text", value: "A COLLEGE FEST THAT SNUCK INTO A SCHOOL" },
      { key: "aboutBodyOne", label: "About — first paragraph", type: "longtext", value: "MADOOZA is the Elden Heights answer to a question nobody asked: what if a fete, a carnival, a cosplay convention and a proper stage night all happened on the same field, on the same day, run entirely by students?" },
      { key: "aboutBodyTwo", label: "About — second paragraph", type: "longtext", value: "Open to every school in Hazaribagh, to parents who claim they're \"just dropping off\", and to anyone in town who hears the soundcheck and follows it. One pass. Everything inside." },
      { key: "aboutPassesLink", label: "About — passes link", type: "text", value: "PASSES →", hint: "The arrow is part of the label text." },
      { key: "aboutDirectionsLink", label: "About — directions link", type: "text", value: "HOW TO GET THERE →", hint: "The arrow is part of the label text." },
      { key: "chaosTitle", label: "Chaos section — heading", type: "text", value: "PICK YOUR CHAOS" },
      { key: "chaosSubtitle", label: "Chaos section — strapline", type: "text", value: "FIVE DOORS, ONE FIELD", hint: "Says \"FIVE\" but the grid hides cards for hidden pages, so this count can go stale — worth rewording to something countless." },
      { key: "sealedEyebrow", label: "Sealed band — kicker", type: "text", value: "STILL SEALED" },
      { key: "sealedTitle", label: "Sealed band — heading", type: "longtext", value: "WE KNOW WHO'S COMING. YOU DON'T." },
      { key: "sealedIntro", label: "Sealed band — paragraph", type: "longtext", value: "A playback singer, a name from your screen, and one act the seniors keep laughing about. Clues drop weekly." },
      { key: "sealedCta", label: "Sealed band — button", type: "text", value: "GO CRACK THE CLUES" },
      { key: "sponsorsEyebrow", label: "Sponsor strip — kicker", type: "text", value: "BACKED BY PEOPLE WHO SAID YES" },
      { key: "sponsorsCta", label: "Sponsor strip — become a sponsor tile", type: "text", value: "BE ON THIS WALL" },
    ],
  },
  {
    key: "lineup",
    title: "Lineup",
    blurb: "The reveal page around the artist cards.",
    slots: [
      { key: "heroEyebrow", label: "Hero eyebrow", type: "text", value: "01 / THE VAULT" },
      { key: "heroTitle", label: "Page heading", type: "text", value: "LINEUP & REVEAL", hint: "Source is \"LINEUP &amp; REVEAL\"; the ampersand is a literal &." },
      { key: "heroIntro", label: "Hero intro paragraph", type: "longtext", value: "Three headline slots are sealed. Each card holds a clue written by the council — tap one to peek, then argue about it with your friends. Names go public on the dates below, no earlier.", hint: "Joined from two source lines; &mdash; renders as an em dash." },
      { key: "artistCardConfirmedLabel", label: "Artist card — revealed status label", type: "text", value: "CONFIRMED", hint: "Shown on every revealed artist card; the name and bio below it come from the backend." },
      { key: "artistCardSealedNote", label: "Artist card — sealed note", type: "text", value: "SEALED UNTIL FURTHER NOTICE" },
      { key: "artistCardClueLabel", label: "Artist card — clue label", type: "text", value: "CLUE" },
      { key: "artistCardHintLabel", label: "Artist card — extra hint label", type: "text", value: "EXTRA CRUMBS" },
      { key: "artistCardPeekButton", label: "Artist card — peek button", type: "text", value: "TAP TO PEEK" },
      { key: "artistCardAnnouncedLabel", label: "Artist card — announced footer", type: "text", value: "ANNOUNCED", hint: "Only the revealed branch is hardcoded; the unrevealed branch uses card.reveal from the backend." },
      { key: "supportEyebrow", label: "Support acts eyebrow", type: "text", value: "ALREADY CONFIRMED" },
      { key: "supportTitle", label: "Support acts heading", type: "text", value: "THE REST OF THE STAGE" },
      { key: "ticketsCtaLabel", label: "Tickets call-to-action", type: "text", value: "GET A PASS BEFORE THE REVEAL" },
    ],
  },
  {
    key: "concert",
    title: "Concert",
    blurb: "The guess-who page around the interest list.",
    slots: [
      { key: "heroEyebrow", label: "Hero kicker", type: "text", value: "05 / THE CONCERT" },
      { key: "heroTitle", label: "Hero heading", type: "text", value: "GUESS WHO." },
      { key: "heroIntro", label: "Hero intro paragraph", type: "longtext", value: "One singer. One 4:30 PM slot on the main stage. No name, no poster, no price — not until the council is ready. Everything we will say is below." },
      { key: "posterRedactedLabel", label: "Silhouette poster label", type: "text", value: "IDENTITY REDACTED" },
      { key: "confirmListTitle", label: "Fact list heading", type: "text", value: "WHAT WE WILL CONFIRM" },
      { key: "confirmItemDateSealed", label: "Fact 4 — date, while sealed", type: "text", value: "A date still under seal — the day drops with the name" },
      { key: "confirmItemDateRevealed", label: "Fact 4 — date, once revealed", type: "text", value: "{date} — gates 9:00 AM", hint: "{date} is date.short from describeDate(); only the trailing gates-time wording is hardcoded copy" },
      { key: "priceCardLabel", label: "Price card label", type: "text", value: "PASS PRICE" },
      { key: "priceCardValue", label: "Price card value", type: "text", value: "SEALED", hint: "Hardcoded placeholder the council will reword when the pass price goes live" },
      { key: "nameCardLabel", label: "Name card label", type: "text", value: "THE NAME" },
      { key: "nameCardValue", label: "Name card value", type: "text", value: "SOON", hint: "Hardcoded placeholder the council will reword at the reveal" },
      { key: "interestCountNote", label: "Interest counter caption", type: "text", value: "{count} HAVE ALREADY PUT THEIR NAME DOWN", hint: "{count} is the live interest count (settings.interestBase, refreshed from /api/stats); only the wording after it is editable" },
      { key: "formEyebrow", label: "Sign-up kicker", type: "text", value: "NO PAYMENT, NO COMMITMENT" },
      { key: "formTitle", label: "Sign-up heading", type: "text", value: "PUT YOUR NAME DOWN" },
      { key: "formIntro", label: "Sign-up intro paragraph", type: "longtext", value: "The interest list gets the name, the date and the price one hour before the rest of Hazaribagh, and a 48-hour window on the {seats} seats. Tell us who you're hoping for while you're here — the council reads every single one.", hint: "{seats} is settings.concertCapacity, formatted en-IN" },
      { key: "formSubmitLabel", label: "Sign-up button", type: "text", value: "TELL ME THE SECOND IT DROPS" },
      { key: "formErrorSubmitFailed", label: "Sign-up failure message", type: "text", value: "Could not join the list — try again" },
      { key: "formErrorGeneric", label: "Fallback error message", type: "text", value: "Something went wrong" },
      { key: "formFootnote", label: "Sign-up small print", type: "text", value: "NO CARD, NO PAYMENT, NO PASS RESERVED · ONE MESSAGE AT THE REVEAL AND NOTHING ELSE" },
      { key: "ticketEyebrow", label: "Confirmation kicker", type: "text", value: "YOU'RE ON THE LIST" },
      { key: "ticketTitle", label: "Confirmation heading", type: "text", value: "NOTED, {name}", hint: "{name} is the submitter's first name, upper-cased; only the wording around it is editable" },
      { key: "ticketIntro", label: "Confirmation paragraph", type: "longtext", value: "You're #{queueNo} on the interest list, down for {seatChoice}. When the name and price go up, you hear first — one hour ahead of the poster.", hint: "{queueNo} is the queue number from the API and {seatChoice} is the chosen seat-count label; both are live values" },
      { key: "ticketPickLabel", label: "Confirmation — requested artist label", type: "text", value: "YOU ASKED FOR" },
      { key: "ticketGuessLabel", label: "Confirmation — guess label", type: "text", value: "YOUR GUESS" },
      { key: "ticketGuessFallback", label: "Confirmation — empty guess text", type: "text", value: "Kept to yourself" },
      { key: "ticketTicketsCta", label: "Confirmation — fete pass link", type: "text", value: "GRAB A FETE PASS MEANWHILE" },
      { key: "ticketResetLabel", label: "Confirmation — add another button", type: "text", value: "ADD SOMEONE ELSE" },
    ],
  },
  {
    key: "cosplay",
    title: "Cosplay",
    blurb: "The arena page around the categories, prizes and entry form.",
    slots: [
      { key: "heroEyebrow", label: "Hero eyebrow", type: "text", value: "03 / THE ARENA" },
      { key: "heroTitle", label: "Page heading", type: "text", value: "COSPLAY CONTEST" },
      { key: "heroIntro", label: "Hero intro paragraph", type: "longtext", value: "Four categories. Solo or squad. A stage walk in front of the whole field at 2:30 PM, and ₹40,000 split across the winners. Registration is {cosplay} an entry, solo or squad, and closes two weeks before gates open — or when 120 entries fill up, whichever lands first.", hint: "{cosplay} is replaced with the live entry fee. The ₹40,000 prize total, the 2:30 PM stage walk and the 120-entry cap are plain text here, so they need editing by hand if they change." },
      { key: "categoryCardKicker", label: "Category card kicker", type: "text", value: "CATEGORY", hint: "The two-digit card number (01, 02, …) is added automatically after this word. The category titles and descriptions themselves already come from the panel." },
      { key: "prizesTitle", label: "Prize pool heading", type: "text", value: "THE PRIZE POOL" },
      { key: "prizesIntro", label: "Prize pool intro", type: "longtext", value: "Cash, trophies, and the merch drop before it goes on sale. Judged by the guest panel — one of whom is still in the vault." },
      { key: "partnersNote", label: "Backing the carnival — note", type: "longtext", value: "The carnival takes its own partners, separately from the fest. Four tiers, from the table that fixes broken wings to the name on the contest itself." },
      { key: "partnersCtaLabel", label: "Backing the carnival — link", type: "text", value: "BACK THE CARNIVAL →" },
      { key: "registerTitle", label: "Entry form heading", type: "text", value: "REGISTER" },
      { key: "submitProcessingLabel", label: "Pay button — while opening payment", type: "text", value: "OPENING PAYMENT…" },
      { key: "submitLabel", label: "Pay button", type: "text", value: "PAY {cosplay} · PUT ME IN THE ARENA", hint: "{cosplay} is replaced with the live entry fee." },
      { key: "entryFinePrint", label: "Entry form small print", type: "longtext", value: "{cosplay} PER ENTRY · A FETE OR CONCERT PASS IS STILL NEEDED · PROPS UNDER 1.2M · NOTHING SHARP, NOTHING THAT FIRES", hint: "{cosplay} is replaced with the live entry fee. The prop rules are plain text." },
      { key: "doneEyebrow", label: "Confirmation eyebrow", type: "text", value: "ENTRY LOGGED" },
      { key: "doneTitle", label: "Confirmation heading", type: "text", value: "SEE YOU AT THE ARENA,", hint: "The entrant's own name is added on the end of this line automatically, so the text should read as a lead-in to a name." },
      { key: "doneBody", label: "Confirmation body", type: "longtext", value: "You're down as {character} in {entryCategory}. Backstage call is 1:45 PM near the science block; stage walk starts at 2:30. We'll message the exact slot the week before.", hint: "{character} and {entryCategory} are filled in from what the entrant submitted (both are shown in bold). The 1:45 PM backstage call and 2:30 stage walk are plain text." },
      { key: "doneFeeNote", label: "Confirmation fee note", type: "longtext", value: "{cosplay} entry fee received. Your slot is held; the fee is non-refundable but transferable to another entrant until entries close.", hint: "{cosplay} is replaced with the live entry fee; the first sentence renders in bold teal." },
      { key: "doneRepairNote", label: "Confirmation repair-kit note", type: "longtext", value: "Bring a repair kit. Every year somebody's armour gives up in the queue and the Art Club runs out of hot glue by noon." },
      { key: "doneResetButton", label: "Register-again button", type: "text", value: "REGISTER SOMEONE ELSE" },
    ],
  },
  {
    key: "fete",
    title: "Fete",
    blurb: "The grounds page around the stall list.",
    slots: [
      { key: "heroEyebrow", label: "Hero eyebrow label", type: "text", value: "05 / THE GROUNDS", hint: "Small numbered kicker; keep it short, it renders in wide letter-spacing caps." },
      { key: "heroTitle", label: "Page heading", type: "text", value: "FETE & CARNIVAL", hint: "Displayed in the display font, all caps." },
      { key: "heroIntro", label: "Hero intro paragraph", type: "longtext", value: "Forty-plus stalls run by clubs, classes and a few very ambitious parents. Everything inside the grounds runs on MADOOZA coins — no cash at any counter, so nobody has to make change while a band is playing.", hint: "Split over three source lines; the dash is an em dash. Stall count (\"Forty-plus\") is written out, not computed." },
      { key: "stallsTitle", label: "Stall grid heading", type: "text", value: "WHERE YOUR COINS WILL GO" },
      { key: "stallRunByLabel", label: "Stall card \"run by\" label", type: "text", value: "RUN BY", hint: "Prefix printed before the stall's backend `run` value, e.g. \"RUN BY Class 11-B\". Only the prefix is hardcoded." },
      { key: "applyTitle", label: "Apply callout heading", type: "text", value: "WANT A STALL?" },
      { key: "applyIntro", label: "Apply callout body", type: "longtext", value: "Clubs, classes and outside vendors can still apply. Fifteen slots left, and the council reviews applications every Friday until the stall list closes, three weeks before gates.", hint: "Split over two source lines. Slot count (\"Fifteen\"), the review day and the closing deadline are all hardcoded here, not read from settings." },
      { key: "applyCtaLabel", label: "Apply button label", type: "text", value: "APPLY FOR A SLOT", hint: "Button only renders when the sponsors page is not hidden; the label text is what is editable, not the link target." },
    ],
  },
  {
    key: "merch",
    title: "Merch",
    blurb: "The shop page around the items and the bag.",
    slots: [
      { key: "heroEyebrow", label: "Hero kicker", type: "text", value: "04 / THE SHOP" },
      { key: "heroTitle", label: "Page heading", type: "text", value: "MERCH DROP" },
      { key: "heroIntro", label: "Hero intro paragraph", type: "longtext", value: "Printed in one run, in Hazaribagh, and never printed again. Pre-order now and collect at the merch tent with your pass code.", hint: "Split across two source lines; joined with a single space." },
      { key: "confirmTitle", label: "Order placed — heading", type: "text", value: "PRE-ORDER PLACED — {total}", hint: "{total} is the live bag total, rendered via formatInr(cartTotal). Keep the token in the text." },
      { key: "confirmBody", label: "Order placed — collection instructions", type: "longtext", value: "Collect at the merch tent on fest day, any time after 10 AM. Bring your pass code. Sizes get swapped at the counter, no drama.", hint: "Split across two source lines; joined with a single space." },
      { key: "confirmResetButton", label: "Order placed — new bag button", type: "text", value: "START A NEW BAG" },
      { key: "itemAddButton", label: "Add-to-bag button", type: "text", value: "ADD" },
      { key: "bagTitle", label: "Bag panel heading", type: "text", value: "YOUR BAG" },
      { key: "bagEmptyNote", label: "Empty bag message", type: "longtext", value: "Nothing in here yet. The hoodie has a clue printed inside the hood, if that helps you decide.", hint: "Split across two source lines; joined with a single space." },
      { key: "placeOrderButton", label: "Place pre-order button", type: "text", value: "PLACE PRE-ORDER" },
      { key: "placeOrderBusyLabel", label: "Place pre-order button (while submitting)", type: "text", value: "PLACING…", hint: "Transient label; ends with a single-character ellipsis." },
      { key: "orderErrorMessage", label: "Pre-order failed message", type: "text", value: "Could not place the pre-order — try again" },
      { key: "orderErrorFallback", label: "Unknown error message", type: "text", value: "Something went wrong" },
      { key: "collectionFootnote", label: "Collection footnote", type: "text", value: "COLLECT AT THE MERCH TENT · PAY ON COLLECTION · SIZES S–XXL ON TEES AND HOODIES", hint: "Three facts separated by middots; the size range uses an en dash." },
    ],
  },
  {
    key: "gallery",
    title: "Gallery",
    blurb: "The build-up page around the photos.",
    slots: [
      { key: "heroEyebrow", label: "Hero kicker", type: "text", value: "06 / EVIDENCE" },
      { key: "heroTitle", label: "Page heading", type: "text", value: "GALLERY" },
      { key: "heroIntro", label: "Hero intro paragraph", type: "longtext", value: "Nothing from the fest itself yet — that's the whole point of a first edition. Until fest day this page is the build-up: paint, plywood, rehearsals, and one very tired council.", hint: "Explains why the grid is pre-fest build-up shots; owner will likely rewrite this after the first edition happens." },
      { key: "submitCardTitle", label: "Submit-photos card heading", type: "text", value: "SHOT SOMETHING GOOD?" },
      { key: "submitCardBody", label: "Submit-photos card body", type: "longtext", value: "Send it in after the fest and it goes up here with your name on it. Photos, phone video, blurry mosh-pit chaos — all welcome." },
      { key: "submitCtaLabel", label: "Submit-photos button label", type: "text", value: "SEND YOUR SHOTS", hint: "Label only. The mailto address already comes from settings.contactEmail and stays live." },
    ],
  },
  {
    key: "sponsors",
    title: "Sponsors",
    blurb: "The partners page around the tiers and the press kit.",
    slots: [
      { key: "heroEyebrow", label: "Hero kicker", type: "text", value: "07 / PARTNERS" },
      { key: "heroTitle", label: "Page heading", type: "text", value: "SPONSORS & PRESS KIT" },
      { key: "heroIntro", label: "Hero intro paragraph", type: "longtext", value: "Expected footfall of 4,000 across one day: students from eleven schools, their families, and most of the town's under-25s. Everything is student-run, which means every rupee is visible and every promise is kept in writing. Two ways to back it: the whole fest, or the cosplay carnival on its own.", hint: "Split across three source lines; join with single spaces. Contains the hardcoded footfall figure (4,000) and school count (eleven)." },
      { key: "tiersTitle", label: "Fest tiers heading", type: "text", value: "FEST-WIDE PARTNER TIERS" },
      { key: "tiersNote", label: "Tiers heading note", type: "text", value: "SIX FEST-WIDE WAYS IN · GST EXTRA · PAID IN TWO INSTALMENTS", hint: "Says 'six' while the tier list itself is backend-driven, so this line goes stale if a tier is added or removed. The cosplay carnival has its own section below." },
      { key: "cosplayTiersTitle", label: "Cosplay tiers heading", type: "text", value: "COSPLAY CARNIVAL PARTNERS" },
      { key: "cosplayTiersNote", label: "Cosplay tiers heading note", type: "text", value: "FOUR WAYS IN · SEPARATE FROM THE FEST LADDER · GST EXTRA" },
      { key: "cosplayTiersIntro", label: "Cosplay tiers intro", type: "longtext", value: "The Cosplay Carnival can be backed on its own, apart from the ladder above. Four categories, up to 120 entries in costume, and a field that stops moving for the 2:30 stage walk. A smaller cheque, pointed at the one hour everybody photographs.", hint: "The 120-entry cap and the 2:30 stage walk are plain text here, so they need editing by hand if they change." },
      { key: "signedEyebrow", label: "Signed sponsors kicker", type: "text", value: "ALREADY ON BOARD" },
      { key: "pressKitTitle", label: "Press kit card heading", type: "text", value: "PRESS KIT" },
      { key: "pressKitIntro", label: "Press kit intro paragraph", type: "longtext", value: "Everything a paper, a page or a partner needs. Please don't stretch the logo — the council will notice.", hint: "Split across two source lines; join with single spaces." },
      { key: "pressKitBadgeLabel", label: "Press kit row 1 — label", type: "text", value: "Badge logo — transparent PNG" },
      { key: "pressKitBadgeMeta", label: "Press kit row 1 — note", type: "text", value: "2000PX ↓" },
      { key: "pressKitFactSheetLabel", label: "Press kit row 2 — label", type: "text", value: "Fact sheet & footfall numbers" },
      { key: "pressKitFactSheetMeta", label: "Press kit row 2 — note", type: "text", value: "ON REQUEST" },
      { key: "pressKitPaletteLabel", label: "Press kit row 3 — label", type: "text", value: "Palette: indigo, teal, crimson" },
      { key: "pressKitPaletteMeta", label: "Press kit row 3 — note", type: "text", value: "4A1382 · 35C6D4 · DF025C", hint: "Borderline: these are hex values, but they are rendered as press-facing copy, not used for styling. Drop this slot if hex strings are to stay in code." },
      { key: "contactTitle", label: "Contact card heading", type: "text", value: "TALK TO THE COUNCIL" },
      { key: "contactIntro", label: "Contact intro paragraph", type: "longtext", value: "Sponsorship, the cosplay carnival, stalls, press passes and anything involving a contract. We reply within two days, faster if you mention food.", hint: "Split across two source lines; join with single spaces. States the two-day reply promise." },
      { key: "contactSponsorshipLabel", label: "Contact row 1 label", type: "text", value: "SPONSORSHIP" },
      { key: "contactPressLabel", label: "Contact row 2 label", type: "text", value: "PRESS" },
      { key: "contactOfficeLabel", label: "Contact row 3 label", type: "text", value: "FEST OFFICE" },
      { key: "contactOfficeHours", label: "Fest office hours", type: "text", value: "weekdays 4–7 PM", hint: "Only the hours are hardcoded; the phone number itself comes from settings.contactPhone and renders before this, joined by ' · '. Store either the hours alone, or the whole line as '{phone} · weekdays 4–7 PM'." },
    ],
  },
  {
    key: "faq",
    title: "FAQ",
    blurb: "The small-print page around the questions.",
    slots: [
      { key: "heroEyebrow", label: "Hero kicker", type: "text", value: "08 / THE SMALL PRINT" },
      { key: "heroTitle", label: "Page heading", type: "text", value: "FAQ + VENUE" },
      { key: "heroIntro", label: "Hero intro paragraph", type: "longtext", value: "The questions the council keeps getting asked in the corridor, answered once, properly." },
      { key: "venueEyebrow", label: "Venue card kicker", type: "text", value: "THE VENUE" },
      { key: "venueName", label: "Venue name", type: "text", value: "THE ELDEN HEIGHTS SCHOOL" },
      { key: "venueAddressLine", label: "Venue address — first line", type: "text", value: "Main grounds, senior block and the assembly canopy", hint: "Renders on its own line, above the city line (the two are separated by a hard line break)." },
      { key: "venueAddressCity", label: "Venue address — second line", type: "text", value: "Hazaribagh, Jharkhand 825301", hint: "Renders directly under the first address line." },
      { key: "venueGettingThereLabel", label: "Getting there — bold lead-in", type: "text", value: "Getting there:" },
      { key: "venueGettingThereBody", label: "Getting there — directions", type: "longtext", value: "ten minutes from the Hazaribagh bus stand, autos run to the main gate all day. Parking is on the far field, entry through the service gate off the back road.", hint: "Continues the same sentence after the bold \"Getting there:\" label, so it starts lowercase." },
      { key: "helpDeskEyebrow", label: "Help desk card kicker", type: "text", value: "ON THE DAY" },
      { key: "helpDeskTitle", label: "Help desk card heading", type: "text", value: "HELP DESK & LOST THINGS" },
      { key: "helpDeskBody", label: "Help desk card body", type: "longtext", value: "Volunteers in gold armbands, help desk beside the coin counter, first aid at the sports room. Lost phones end up at the help desk within the hour, they always do." },
      { key: "helpDeskCtaLabel", label: "Help desk call link label", type: "text", value: "CALL THE FEST OFFICE", hint: "Only the label is a copy slot. The number it dials (tel:+919122280578) is still hardcoded in the markup and belongs in settings next to contactEmail, not in the copy store." },
      { key: "stillStuckTitle", label: "Contact card heading", type: "text", value: "STILL STUCK?" },
      { key: "stillStuckBody", label: "Contact card body", type: "text", value: "Ask anything and a very real student will answer, usually between classes.", hint: "The email address below it already comes from settings.contactEmail — leave that as is." },
    ],
  },
  {
    key: "tickets",
    title: "Tickets",
    blurb: "The passes page around the checkout.",
    slots: [
      { key: "heroEyebrow", label: "Hero kicker", type: "text", value: "02 / ENTRY" },
      { key: "heroTitle", label: "Page heading", type: "text", value: "ONE PASS ON SALE." },
      { key: "heroIntro", label: "Hero intro paragraph", type: "longtext", value: "The whole fest — every stall, every stage, the cosplay arena — runs on the Fete Pass, and it's live now. The concert is a ticketed show of its own: the singer and the price are both still sealed." },
      { key: "heroGatesNoteSealed", label: "Gates note (date still sealed)", type: "longtext", value: "Your pass works whatever day it lands on. Gates 9:00 AM either way.", hint: "Shown only while the fest date is sealed; the sibling note below replaces it once the date is revealed." },
      { key: "heroGatesNoteRevealed", label: "Gates note (date revealed)", type: "longtext", value: "Gates 9:00 AM. Bring the pass code, we'll do the rest.", hint: "Shown only after the date is revealed in settings." },
      { key: "successTitle", label: "Purchase confirmed — heading", type: "text", value: "YOU'RE IN" },
      { key: "successDateLine", label: "Purchase confirmed — date strip", type: "text", value: "{date} · GATES 9:00 AM", hint: "{date} is the short fest date from describeDate() — only the ' · GATES 9:00 AM' half is hardcoded today." },
      { key: "successPassCodeLabel", label: "Receipt label — pass code", type: "text", value: "PASS CODE" },
      { key: "successNameLabel", label: "Receipt label — name", type: "text", value: "NAME" },
      { key: "successPaidLabel", label: "Receipt label — amount paid", type: "text", value: "PAID" },
      { key: "successNote", label: "Purchase confirmed — collection note", type: "longtext", value: "A copy is on its way to your phone. Screenshot this, or just tell the gate volunteer your pass code — they have the list. Coin counters are right past the arch." },
      { key: "successCosplayCta", label: "Purchase confirmed — cosplay button", type: "text", value: "NOW REGISTER FOR COSPLAY" },
      { key: "successBuyAgainCta", label: "Purchase confirmed — buy again button", type: "text", value: "BUY ANOTHER SET" },
      { key: "fetePassKicker", label: "Fete pass card — kicker", type: "text", value: "FETE PASS · DAYTIME" },
      { key: "fetePassBadge", label: "Fete pass card — status badge", type: "text", value: "ON SALE NOW" },
      { key: "concertPassKicker", label: "Concert pass card — kicker", type: "text", value: "CONCERT PASS · SEALED UNTIL THE REVEAL" },
      { key: "concertPassPriceLabel", label: "Concert pass card — price placeholder", type: "text", value: "PRICE SEALED" },
      { key: "concertPassCta", label: "Concert pass card — badge link", type: "text", value: "GUESS WHO →" },
      { key: "concertSeatsNote", label: "Concert pass card — capacity note", type: "text", value: "{seats} SEATS ONLY", hint: "{seats} is settings.concertCapacity, already formatted with Indian digit grouping." },
      { key: "passRulesNote", label: "Pass rules footnote", type: "longtext", value: "Cosplay contest entry is {cosplay} on top of any pass — register on the Cosplay page. Under-14s from outside the school need an accompanying adult pass. Fete Pass holders can upgrade at the gate for the difference, subject to concert capacity.", hint: "The source hardcodes ₹400 here even though settings.cosplayFee exists, so it drifts — store it as {cosplay}. 'Cosplay page' is a link when the cosplay page is live and plain text when it is hidden; keep it as a phrase in the copy." },
      { key: "checkoutTitle", label: "Checkout panel heading", type: "text", value: "CHECKOUT" },
      { key: "checkoutPassName", label: "Checkout — selected pass name", type: "text", value: "FETE PASS" },
      { key: "checkoutPassPrice", label: "Checkout — per-pass price line", type: "text", value: "{fete} EACH", hint: "{fete} is settings.fetePrice via formatInr(); only the word 'EACH' is hardcoded today." },
      { key: "checkoutConcertNote", label: "Checkout — concert pass note", type: "text", value: "CONCERT PASSES OPEN WITH THE REVEAL" },
      { key: "checkoutConcertLinkLabel", label: "Checkout — concert interest link", type: "text", value: "REGISTER YOUR INTEREST" },
      { key: "checkoutPayProcessing", label: "Pay button — processing label", type: "text", value: "OPENING PAYMENT…" },
      { key: "checkoutPayCta", label: "Pay button", type: "text", value: "PAY {total} · GET MY PASS", hint: "{total} is the running order total (quantity × pass price), filled in by the page" },
      { key: "checkoutSoldOut", label: "Sold-out replacement for the pay button", type: "text", value: "SOLD OUT — JOIN THE WAITLIST" },
      { key: "checkoutPaymentNote", label: "Checkout footnote", type: "longtext", value: "PASSES ARE PROCESSED BY RAZORPAY. YOUR PASS CODE IS ISSUED THE MOMENT PAYMENT CLEARS." },
    ],
  },
  {
    key: "footer",
    title: "Footer",
    blurb: "The block at the bottom of every page.",
    slots: [
      { key: "brandWordmark", label: "Footer brand wordmark", type: "text", value: "MADOOZA", hint: "The fest name as it appears in the footer, above the blurb." },
      { key: "brandBlurb", label: "Footer brand blurb", type: "longtext", value: "The Voice of Hazaribagh. Built, painted, wired and shouted about by the students of The Elden Heights School.", hint: "Joined from two source lines. Two sentences; keep it short, it is capped at 30ch width." },
      { key: "schoolName", label: "School name (beside crest)", type: "text", value: "THE ELDEN HEIGHTS SCHOOL", hint: "Rendered in all caps with wide letter-spacing; a line break follows it before the motto." },
      { key: "schoolMotto", label: "School motto (beside crest)", type: "text", value: "TOWARDS ETERNAL GLORY", hint: "Rendered in all caps in a dimmer colour." },
      { key: "festColumnTitle", label: "Column 1 heading", type: "text", value: "THE FEST", hint: "Small all-caps column label." },
      { key: "festLinkLineup", label: "Column 1 link — Lineup", type: "text", value: "Lineup & reveal", hint: "Label only; the link target /lineup and its show/hide stay in code and settings." },
      { key: "festLinkConcert", label: "Column 1 link — Concert", type: "text", value: "The concert · guess who", hint: "Label only; links to /concert. Contains a middot separator." },
      { key: "festLinkCosplay", label: "Column 1 link — Cosplay", type: "text", value: "Cosplay contest", hint: "Label only; links to /cosplay." },
      { key: "festLinkFete", label: "Column 1 link — Fete", type: "text", value: "Fete & stalls", hint: "Label only; links to /fete." },
      { key: "festLinkGallery", label: "Column 1 link — Gallery", type: "text", value: "Gallery", hint: "Label only; links to /gallery." },
      { key: "getInColumnTitle", label: "Column 2 heading", type: "text", value: "GET IN", hint: "Small all-caps column label." },
      { key: "getInLinkTickets", label: "Column 2 link — Tickets", type: "text", value: "Passes & tickets", hint: "Label only; links to /tickets." },
      { key: "getInLinkMerch", label: "Column 2 link — Merch", type: "text", value: "Merch shop", hint: "Label only; links to /merch." },
      { key: "getInLinkSponsors", label: "Column 2 link — Sponsors", type: "text", value: "Sponsors & press kit", hint: "Label only; links to /sponsors." },
      { key: "getInLinkFaq", label: "Column 2 link — FAQ", type: "text", value: "FAQ + venue", hint: "Label only; links to /faq." },
      { key: "officeColumnTitle", label: "Column 3 heading", type: "text", value: "FEST OFFICE", hint: "Small all-caps column label." },
      { key: "officeAddressSchool", label: "Fest office — first address line", type: "text", value: "The Elden Heights School", hint: "A line break follows it. The email and phone below come from settings and are not slots." },
      { key: "officeAddressCity", label: "Fest office — second address line", type: "text", value: "Hazaribagh, Jharkhand", hint: "City and state line, directly under the school name." },
      { key: "copyrightLine", label: "Copyright line", type: "text", value: "© {year} MADOOZA · STUDENT COUNCIL, ELDEN HEIGHTS", hint: "{year} is settings.festYear, interpolated live. The rest of the line is hardcoded. The date strip to its right (line 112) is fully derived from describeDate()/settings and is not a slot." },
    ],
  },
];
